
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8090/eureka/
server:
  port: 8084

feign:
  hystrix:
    enabled: true

spring:
  application:
    name: service-feign
  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    suffix: .html
  data:
    solr:
      host: http://127.0.0.1:8080/solr